// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjqtO2XEvDARLsQOyNrtdebVX0KiOgVYs',
    appId: '1:386757460223:web:5defb738ca7afea9894cca',
    messagingSenderId: '386757460223',
    projectId: 'diy-home-improvement-store',
    authDomain: 'diy-home-improvement-store.firebaseapp.com',
    storageBucket: 'diy-home-improvement-store.firebasestorage.app',
    measurementId: 'G-0RFH51M199',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrR24RNIUlGprKnjnns8p3C_ciXO7yw3g',
    appId: '1:386757460223:android:872021b0a0d9dc03894cca',
    messagingSenderId: '386757460223',
    projectId: 'diy-home-improvement-store',
    storageBucket: 'diy-home-improvement-store.firebasestorage.app',
  );
}
